export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',
    
    UPDATE_USER_STATE: "UPDATE_USER_STATE"
};

export const alertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};

export const boardConstants = {
    CREATE_BOARD_REQUEST: 'CREATE_BOARD_REQUEST',
    CREATE_BOARD_SUCCESS: 'CREATE_BOARD_SUCCESS',
    CREATE_BOARD_FAILURE: 'CREATE_BOARD_FAILURE',

    GET_BOARDS_REQUEST: 'GET_BOARDS_REQUEST',
    GET_BOARDS_SUCCESS: 'GET_BOARDS_SUCCESS',
    GET_BOARDS_FAILURE: 'GET_BOARDS_FAILURE',
    
    GET_BOARD_REQUEST: 'GET_BOARD_REQUEST',
    GET_BOARD_FAILURE: 'GET_BOARD_FAILURE',
    GET_BOARD_SUCCESS: 'GET_BOARD_SUCCESS',

    CHANGE_BOARD_TITLE: 'CHANGE_BOARD_TITLE',

    DELETE_BOARD: 'DELETE_BOARD',

    ADD_LIST_TO_BOARD: 'ADD_LIST_TO_BOARD',

    UPDATE_CURRENT_BOARD_ID: 'UPDATE_CURRENT_BOARD_ID'
}

export const listConstants = {
    ADD_LIST: 'ADD_LIST',
    GETTING_LIST: 'GETTING_LIST'
}